services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - big_data_db_data:/var/lib/postgresql/data
  api:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:80
    profiles:
      - prod
volumes:
  big_data_db_data:
